### ISSUE TITLE
Rename on PackageControl channel

### ISSUE THREAD

**Issue by pykong** [akrabat/HideSidebarWhenNotFocussed#11]
After renaming to SideBarHider that change must now make its way to **PackageControl**.
The old name unfortunately still stands, as it is not sourced from the repo name, as seen in the link:
https://packagecontrol.io/packages/Hide%20Sidebar%20When%20Not%20Focussed

In order to do so, a new PR to the package control channel has to be opened.

**Comment by pykong** [comment]
I am right now too busy to do it, as I am working on a very big update of a major Sublime Text plugin.
P.S.: **SideBarHider** is trending on **PackageControl**. :+1:

**Comment by akrabat** [comment]
Done: https://github.com/wbond/package_control_channel/pull/6754
