### ISSUE TITLE
Rename to HideSidebarOnBlur

### ISSUE THREAD

**Issue by pykong** [akrabat/HideSidebarWhenNotFocussed#4]
I feel HideSidebarOnBlur is shorter, not so unwieldy word as the current name. Shortness has many advantages. But foremost it is much sexier.

We are targeting a developer community with our plugin, therefore the term **blur** is clearly understood by the common user.

**Comment by akrabat** [comment]
:)

Laptop broke while I'm here, so may take longer to catch up than I'd hoped…

**Comment by pykong** [comment]
Sure take your time...

**Comment by pykong** [comment]
@akrabat Still struggling with setting things right, after your laptop broke?

**Comment by akrabat** [comment]
Incompetence on my part. Sorry. Doing now!

**Comment by pykong** [comment]
@akrabat No need to apologize. We both know how messy a developer's life can be from time to time.

**Comment by pykong** [comment]
@akrabat I have just tested: The plugin runs fine with the new command name.
I should update the README.md though, as the toggle command can not be found with the command name itself as query string.

The question is: Would you like to rename the plugin, to give it a shorter more beautiful name?
I would prepare a message to be shown to the user in that case.

**HideSidebarOnBlur** sounds so much better to me.

Also if you like me to co-maintain the package, I am willing to help out.
I am already doing so for two other plugins, including the popular [FocusFileOnSidebar](https://github.com/miguelgraz/FocusFileOnSidebar) which many use together with this sidebar plugin.
(They really enhance each other).

Of course, both choices are entirely up to you. You are the author.

**Comment by pykong** [comment]
Maybe an even shorter name is also good.
What about:

- SideBarCloak
- CloakSideBar
- SideBarHider
- HideSideBar

The focus loss as the essential trigger event of this plugin does not necessarily need to be reflected in the name itself. It can just fit into the description. I believe people will automatically assume an auto hider for the sidebar will work with blur events. What else would make sense?

**Comment by akrabat** [comment]
I've added you as a collaborator - thanks for your work so far :)

Also happy with a new name, though I'm not a fan of _HideSideBarOnBlur_ as it relies on technical knowledge (that "blur" means to lose focus) to understand.

_SideBarHider_,  _HideSideBar_ or  _AutoHideSideBar_ work for me. Do you have a preference?

**Comment by akrabat** [comment]
There's already an Auto Hide Sidebar (https://github.com/xunker/autohidesidebar), so that rules out _HideSideBar_ and _AutoHideSideBar_

Maybe _HideSidebarOnBlur_ is okay. It's either that or _SidebarHider_

**Comment by pykong** [comment]
Thank you for your trust, Rob!

I just started a topic on Sublime Forum: [here](https://forum.sublimetext.com/t/new-name-for-hidesidebarwhennotfocussed-your-suggestions/31059). Maybe someone comes up with an even better name.

I am still going to ask for your blessing before renaming and publishing the next release to PackageControl. Other than that you can relax and enjoy the ride, I will handle everything necessary for the next release.

**Comment by pykong** [comment]
Other suggestions from the thread:
- **HideBar** a wordplay conveying both "hiding" and "SideBar"
- **ZenBar** in the style of the highly popular "ZenTabs" plugin, which removes Tabs.
- **AutoSlideBar** another wordplay alluding to the sliding animation of the SideBar.

@akrabat  Among all options discussed in this thread, is there a clear favorite of yours?
_And congrats to your new avatar pic!_

**Comment by akrabat** [comment]
I'm reasonably easy tbh. Though not ZenBar :)

**Comment by pykong** [comment]
OK. Let's not make a science out of it. :-)

I say we will go with **SideBarHider**

- It is short. _(Less than half the size of the current name! 12/26 chars)_
- Yet, very comprehensible.

No, smart word play, here. After all, we have the only no-nonsense plugin of its kind, the name should reflect that quality. :+1: 

I am going to prepare the release. Should be ready by next weekend.

**Comment by akrabat** [comment]
Works for me!

**Comment by pykong** [comment]
@akrabat 

Released.

I made all necessary file changes and added messages informing the user about the renaming and our new toggle command.

You may also rename the repository itself. There will always be a redirect from the old name/URL.

**Comment by akrabat** [comment]
Done.

Thanks!
